services:
    VysokeSkoly\AppStatusBundle\Services\AppStatusCollector:
        arguments:
            - "%kernel.project_dir%"
            - "%app_status.source_file%"
            - "%app_status.main_status_key%"
        public: false
        tags:
            - { name: data_collector, template: "@AppStatus/Profiler/index.html.twig", id: appStatus }
