services:
    VysokeSkoly\AppStatusBundle\Services\AppStatusCollector:
        public: false
        arguments:
            $projectRoot: '%kernel.project_dir%'
            $appStatusFilePath: '%app_status.source_file%'
            $mainStatusKey: '%app_status.main_status_key%'
            $envFile: '%app_status.env_file%'
        tags:
            - { name: data_collector, template: '@VysokeSkolyAppStatus/Profiler/index.html.twig', id: 'appStatus' }
